language: bash

sudo: required
services:
  - docker

addons:
  apt:
    packages:
    - build-essential
    - grep
    - sed
script: ". ./script/cibuild"

before_install:
- openssl aes-256-cbc -K $encrypted_af135e3dfc23_key -iv $encrypted_af135e3dfc23_iv
  -in enc.tar.gz.enc -out enc.tar.gz -d
