language: bash

sudo: required
services:
  - docker

addons:
  apt:
    packages:
    - build-essential
    - grep
    - sed
script: ". ./script/cibuild"

before_install:
 - openssl aes-256-cbc -pass "pass:$pass" -in key.gpg.enc -out key.gpg -d -a
